spring.application.name=springbootdemo
#type.food = choco
spring.data.jpa.repositories.enabled=true

spring.datasource.url=jdbc:mysql://localhost:3306/springbootdemo?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=DAHdah321#@!

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#This below config show each and every Db calls
#if it is true ot default is true if not defined then we not able to see multiple db calls, as it shows persist behaviour
#With OSIV enabled, Spring keeps the same Hibernate Session / Persistence Context alive for the entire web request:
spring.jpa.open-in-view=false