spring.application.name=springbootdemo
#type.food = choco
spring.data.jpa.repositories.enabled=true

spring.datasource.url=jdbc:mysql://localhost:3306/springbootdemo?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=DAHdah321#@!

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#This below config show each and every Db calls
#if it is true ot default is true if not defined then we not able to see multiple db calls, as it shows persist behaviour
#With OSIV enabled, Spring keeps the same Hibernate Session / Persistence Context alive for the entire web request:
spring.jpa.open-in-view=false
external.api.base-url = https://dummy.restapiexample.com/api/v1
#logging config
logging.level.com.module1.springbootdemo.h4.clients = DEBUG
logging.level.root = INFO
logging.pattern.console=%d{dd-MM-yy HH:mm:ss} [%level] [%c{1}] --- %m%n
#logging.file.name=application.log - to write logs in a file
#logging.config=classpath:logbackfile.xml
# actuator config
management.endpoints.web.exposure.include=*
management.info.env.enabled=true
info.app.author = Tanish Dahiya
info.app.version=1.0.0
info.app.documentation=https://google.com
management.endpoint.env.show-values=always
management.info.build.enabled=true
management.info.git.enabled=true
management.info.java.enabled=true
management.info.os.enabled=true

#spring security
#spring.security.user.name=td
##spring.security.user.password=123456


spring.security.secret = testing32187387378djhdbnjdnmdnkjdiijhddijhKey
# 1 hour expiration
jwt.expiration=3600000